// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfG1NtyWAJu60wsZlRVHnHe_0EFFG-NoA',
    appId: '1:897599091699:android:b659584786a2c861e15886',
    messagingSenderId: '897599091699',
    projectId: 'quiz-aa0a0',
    databaseURL: 'https://quiz-aa0a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-aa0a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2u-LDC3AJPb322JHFjlvL5LDnNJvmYnE',
    appId: '1:897599091699:ios:d1a4270986ccc79ee15886',
    messagingSenderId: '897599091699',
    projectId: 'quiz-aa0a0',
    databaseURL: 'https://quiz-aa0a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-aa0a0.appspot.com',
    iosBundleId: 'com.example.quiz',
  );
}
